const Characters = {
  Bloodhound: true,
  Gibraltar: true,
  Lifeline: true,
  Pathfinder: true,
  Wraith: true,
  Bangalore: true,
  Caustic: true,
  Mirage: true,
  Octane: true,
  Wattson: true,
  Crypto: true,
  Revenant: true,
  Loba: true,
  Rampart: true,
  Horizon: true,
  Fuse: true,
  Valkyrie: true,
  Seer: true,
  Ash: true,
  "Mad Maggie": true,
  "New Castle": true,
  Vantage: true,
  Catalyst: true,
  Ballistic: true,
};

const colors = {
  primar: "",
  second: "",
  terce: "",
  quadra: "",
  green: "#2E7D32",
  red: "#B71C1C",
};
